# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  csproject: '**/*.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  restClientPackageName: 'ECommerce.Rest.Client.Api'

steps:
- task: NuGetToolInstaller@1

- task: CmdLine@2
  displayName: 'swagger-codegen'
  inputs:
    script: 'java -jar tools\swagger-codegen-cli-3.0.21.jar generate -i ECommerce.Api\Swagger.json -l csharp -o -DpackageName=$(restClientPackageName)'
    workingDirectory: '$(Build.Repository.LocalPath)'
  
- task: CmdLine@2
  inputs:
    script: 'build.bat'
    workingDirectory: '$(Build.Repository.LocalPath)\$(restClientPackageName)' 

- task: NuGetCommand@2
  displayName: 'restore'
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'

- task: VSBuild@1
  inputs:
    solution: '**\*.sln'
    msbuildArgs: '/p:OutputPath="$(Build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: |
              '$(csproject)'
              '!**/$(restClientPackageName).csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'


- task: NuGetCommand@2
  displayName: 'pack'
  inputs:
    command: 'pack'
    packagesToPack: '**/$(restClientPackageName).csproj'
    versioningScheme: 'byPrereleaseNumber'
    majorVersion: '1'
    minorVersion: '0'
    patchVersion: '0'
    verbosityPack: 'Normal'

- task: NuGetCommand@2
  displayName: 'push'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '46a4dd82-34fb-4605-9cd7-d70020e50202/c82446dc-a554-4e59-b571-ce7f95e14cd7'
  

