name: $(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  csproject: '**/*.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  restClientPackageName: 'ECommerce.Rest.Client.Api'

steps:
# For swagger-codegen
- template: codegen-run.yml
  parameters: 
    apiVersions: ["v1", "v2"]
    workingDirectory: '$(Build.Repository.LocalPath)'
    restClientPackageName: '$(restClientPackageName)'

- task: NuGetToolInstaller@1

# For swagger-codegen
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    projects: |
      **/*Rest.Client*.csproj
      !**/*.Test.csproj
    arguments: '--configuration $(buildConfiguration)'

# For swagger-codegen
- task: NuGetCommand@2
  displayName: 'dotnet pack'
  inputs:
    command: 'pack'
    packagesToPack: '**/*Rest.Client*.csproj;!**/*.Test.csproj'
    versioningScheme: 'byBuildNumber'

- task: NuGetCommand@2
  displayName: 'nuget push'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '46a4dd82-34fb-4605-9cd7-d70020e50202/c82446dc-a554-4e59-b571-ce7f95e14cd7'
  