name: $(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  csproject: '**/*.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  restClientPackageName: 'ECommerce.Rest.Client.Api'
  apiVersionList: 'v1 v2'

steps:
# For swagger-codegen
- task: CmdLine@2
  displayName: 'swagger-codegen'
  inputs:
    script: 'for %x in ($(apiVersionList)) do java -jar tools\swagger-codegen-cli-3.0.21.jar generate -i ECommerce.Api\Swagger%x.json -l csharp -o $(restClientPackageName).%x -DpackageName=$(restClientPackageName).%x'
    workingDirectory: '$(Build.Repository.LocalPath)'

- task: NuGetToolInstaller@1

# For swagger-codegen
- task: CmdLine@2
  inputs:
    script: 'build.bat'
    workingDirectory: '$(Build.Repository.LocalPath)\$(restClientPackageName)' 

- task: NuGetCommand@2
  displayName: 'restore'
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'

# For swagger-codegen
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**\*Rest.Client*.csproj'
    arguments: '--configuration $(buildConfiguration)'

# For swagger-codegen
- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '**\*Rest.Client*.csproj;!**\*.Test.csproj'
    versioningScheme: 'byBuildNumber'

- task: NuGetCommand@2
  displayName: 'push'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '46a4dd82-34fb-4605-9cd7-d70020e50202/c82446dc-a554-4e59-b571-ce7f95e14cd7'
  